# Generated by Django 2.0.4 on 2018-05-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='email',
            field=models.EmailField(default='rohan.me2014@gmail.com', max_length=254),
        ),
    ]
