# Generated by Django 2.0.4 on 2018-05-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_contactdata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
