# Generated by Django 2.0.4 on 2018-05-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20180504_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatesubscribe',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
